### ISSUE TITLE
setting up plix email 

### ISSUE THREAD

**Issue by 1l2p** [ml-learning/plix-staging#1]
Would it make sense to set up a "generic" plix email, e.g. plix@media.mit.edu or publiclibaries@media.mit.edu for all incoming contact requests? I noticed that throughout the site, we're currently communicating Helen's MIT address. Having a more generic address would make sense, and could be forwarded to a number of people.

**Comment by kitsandkats** [comment]
We have a plix email, it's libraries@media.mit.edu
