### ISSUE TITLE
Opening remote links in new tab

### ISSUE THREAD

**Issue by 1l2p** [ml-learning/plix-staging#2]
When navigating away from PLIX to one of the project sites, the link loads in the currrent window (e.g. http://learn.media.mit.edu/plix-staging/activities/databasic clicking on the links to "View the workshop activities"). I think it would make more sense to open those links in new tabs or windows.

**Comment by hakbailey** [comment]
My understanding from our UX team is that best practice is to not open links (even external ones) in a new tab unless there is data on the current page that would be lost if the user navigated away from it. We can talk more about this though if you feel strongly about it.

**Comment by 1l2p** [comment]
Good point and yes it makes sense as the default. My suggestion was a result of feeling "surprised" when the link took me to a new site. When I am browsing through the available activities on PLIX I wanted to stay on the site. Maybe we should just mark external links as such, so people are not surprised.
